/** Strings introduced by the OpenAI Endpoint / ChatGPT provider selector. */
export const aiProviderStrings = {
  zh: {
    setSecAiProvider: 'AI 提供商',
    onbLocalAi: 'NiuOffice AI 可使用 OpenAI Endpoint 或 ChatGPT',
    onbNote3: '使用正在运行的 OpenAI Endpoint 服务器，或登录您的 ChatGPT 订阅。',
    aiProviderChoose: '选择 NiuOffice AI 的连接方式。',
    aiProviderLmStudioHint: '使用 Bearer API 密钥的 OpenAI 兼容服务器',
    aiProviderChatGptHint: '使用您的 ChatGPT 订阅',
    aiProviderOpenSettings: '打开 AI 提供商设置',
    chatGptConnectedPlan: '已连接 · {plan}',
    chatGptSignedOut: '需要登录',
    chatGptUnavailable: 'ChatGPT 连接不可用',
    chatGptDescription: '在浏览器中安全登录，以使用您的 ChatGPT 套餐。',
    chatGptSignIn: '使用 ChatGPT 登录',
    chatGptSigningIn: '正在等待浏览器登录…',
    chatGptSignOut: '退出登录',
    chatGptAccount: '账户',
    chatGptPlan: '套餐',
    chatGptUsage: '使用情况',
    chatGptPrimaryLimit: '主要限制',
    chatGptSecondaryLimit: '次要限制',
    chatGptUsagePercent: '已使用 {percent}%',
    chatGptResetsAt: '{time} 重置',
    chatGptRateLimited: '已达到使用限制',
    chatGptOperationFailed: '操作失败，请重试。',
  },
  en: {
    setSecAiProvider: 'AI Provider',
    onbLocalAi: 'NiuOffice AI works with OpenAI Endpoint or ChatGPT',
    onbNote3: 'Use a running OpenAI Endpoint server or sign in with your ChatGPT subscription.',
    aiProviderChoose: 'Choose how NiuOffice AI connects.',
    aiProviderLmStudioHint: 'OpenAI-compatible server authenticated with a Bearer API key',
    aiProviderChatGptHint: 'Use your ChatGPT subscription',
    aiProviderOpenSettings: 'Open AI provider settings',
    chatGptConnectedPlan: 'Connected · {plan}',
    chatGptSignedOut: 'Sign in required',
    chatGptUnavailable: 'ChatGPT connection unavailable',
    chatGptDescription: 'Sign in securely in your browser to use your ChatGPT plan.',
    chatGptSignIn: 'Sign in with ChatGPT',
    chatGptSigningIn: 'Waiting for browser sign-in…',
    chatGptSignOut: 'Sign out',
    chatGptAccount: 'Account',
    chatGptPlan: 'Plan',
    chatGptUsage: 'Usage',
    chatGptPrimaryLimit: 'Primary limit',
    chatGptSecondaryLimit: 'Secondary limit',
    chatGptUsagePercent: '{percent}% used',
    chatGptResetsAt: 'Resets {time}',
    chatGptRateLimited: 'Usage limit reached',
    chatGptOperationFailed: 'The operation failed. Please try again.',
  },
  ja: {
    setSecAiProvider: 'AI プロバイダー',
    onbLocalAi: 'NiuOffice AI は OpenAI Endpoint または ChatGPT で利用できます',
    onbNote3:
      '実行中の OpenAI Endpoint サーバーを使用するか、ChatGPT サブスクリプションでサインインしてください。',
    aiProviderChoose: 'NiuOffice AI の接続方法を選択します。',
    aiProviderLmStudioHint: 'Bearer API キーで認証する OpenAI 互換サーバー',
    aiProviderChatGptHint: 'ChatGPT サブスクリプションを使用',
    aiProviderOpenSettings: 'AI プロバイダー設定を開く',
    chatGptConnectedPlan: '接続済み · {plan}',
    chatGptSignedOut: 'サインインが必要です',
    chatGptUnavailable: 'ChatGPT 接続を利用できません',
    chatGptDescription: 'ブラウザーで安全にサインインして ChatGPT プランを使用します。',
    chatGptSignIn: 'ChatGPT でサインイン',
    chatGptSigningIn: 'ブラウザーでのサインインを待っています…',
    chatGptSignOut: 'サインアウト',
    chatGptAccount: 'アカウント',
    chatGptPlan: 'プラン',
    chatGptUsage: '使用状況',
    chatGptPrimaryLimit: '主な制限',
    chatGptSecondaryLimit: '副次的な制限',
    chatGptUsagePercent: '{percent}% 使用済み',
    chatGptResetsAt: '{time} にリセット',
    chatGptRateLimited: '使用上限に達しました',
    chatGptOperationFailed: '操作に失敗しました。もう一度お試しください。',
  },
  ko: {
    setSecAiProvider: 'AI 공급자',
    onbLocalAi: 'NiuOffice AI는 OpenAI Endpoint 또는 ChatGPT와 함께 작동합니다',
    onbNote3: '실행 중인 OpenAI Endpoint 서버를 사용하거나 ChatGPT 구독으로 로그인하세요.',
    aiProviderChoose: 'NiuOffice AI 연결 방식을 선택하세요.',
    aiProviderLmStudioHint: 'Bearer API 키로 인증하는 OpenAI 호환 서버',
    aiProviderChatGptHint: 'ChatGPT 구독 사용',
    aiProviderOpenSettings: 'AI 공급자 설정 열기',
    chatGptConnectedPlan: '연결됨 · {plan}',
    chatGptSignedOut: '로그인 필요',
    chatGptUnavailable: 'ChatGPT 연결을 사용할 수 없음',
    chatGptDescription: '브라우저에서 안전하게 로그인하여 ChatGPT 요금제를 사용하세요.',
    chatGptSignIn: 'ChatGPT로 로그인',
    chatGptSigningIn: '브라우저 로그인을 기다리는 중…',
    chatGptSignOut: '로그아웃',
    chatGptAccount: '계정',
    chatGptPlan: '요금제',
    chatGptUsage: '사용량',
    chatGptPrimaryLimit: '기본 한도',
    chatGptSecondaryLimit: '보조 한도',
    chatGptUsagePercent: '{percent}% 사용됨',
    chatGptResetsAt: '{time}에 초기화',
    chatGptRateLimited: '사용 한도에 도달함',
    chatGptOperationFailed: '작업에 실패했습니다. 다시 시도하세요.',
  },
  fr: {
    setSecAiProvider: 'Fournisseur d’IA',
    onbLocalAi: 'NiuOffice AI fonctionne avec OpenAI Endpoint ou ChatGPT',
    onbNote3:
      'Utilisez un serveur OpenAI Endpoint actif ou connectez-vous avec votre abonnement ChatGPT.',
    aiProviderChoose: 'Choisissez comment NiuOffice AI se connecte.',
    aiProviderLmStudioHint: 'Serveur compatible OpenAI authentifié par clé API Bearer',
    aiProviderChatGptHint: 'Utiliser votre abonnement ChatGPT',
    aiProviderOpenSettings: 'Ouvrir les réglages du fournisseur d’IA',
    chatGptConnectedPlan: 'Connecté · {plan}',
    chatGptSignedOut: 'Connexion requise',
    chatGptUnavailable: 'Connexion à ChatGPT indisponible',
    chatGptDescription:
      'Connectez-vous en toute sécurité dans votre navigateur pour utiliser votre offre ChatGPT.',
    chatGptSignIn: 'Se connecter avec ChatGPT',
    chatGptSigningIn: 'En attente de la connexion dans le navigateur…',
    chatGptSignOut: 'Se déconnecter',
    chatGptAccount: 'Compte',
    chatGptPlan: 'Offre',
    chatGptUsage: 'Utilisation',
    chatGptPrimaryLimit: 'Limite principale',
    chatGptSecondaryLimit: 'Limite secondaire',
    chatGptUsagePercent: '{percent} % utilisé',
    chatGptResetsAt: 'Réinitialisation à {time}',
    chatGptRateLimited: 'Limite d’utilisation atteinte',
    chatGptOperationFailed: 'L’opération a échoué. Réessayez.',
  },
  de: {
    setSecAiProvider: 'KI-Anbieter',
    onbLocalAi: 'NiuOffice AI funktioniert mit OpenAI Endpoint oder ChatGPT',
    onbNote3:
      'Verwenden Sie einen laufenden OpenAI Endpoint-Server oder melden Sie sich mit Ihrem ChatGPT-Abonnement an.',
    aiProviderChoose: 'Wählen Sie, wie NiuOffice AI eine Verbindung herstellt.',
    aiProviderLmStudioHint: 'OpenAI-kompatibler Server mit Bearer-API-Schlüssel',
    aiProviderChatGptHint: 'Ihr ChatGPT-Abonnement verwenden',
    aiProviderOpenSettings: 'KI-Anbietereinstellungen öffnen',
    chatGptConnectedPlan: 'Verbunden · {plan}',
    chatGptSignedOut: 'Anmeldung erforderlich',
    chatGptUnavailable: 'ChatGPT-Verbindung nicht verfügbar',
    chatGptDescription:
      'Melden Sie sich sicher im Browser an, um Ihren ChatGPT-Tarif zu verwenden.',
    chatGptSignIn: 'Mit ChatGPT anmelden',
    chatGptSigningIn: 'Warten auf Browser-Anmeldung…',
    chatGptSignOut: 'Abmelden',
    chatGptAccount: 'Konto',
    chatGptPlan: 'Tarif',
    chatGptUsage: 'Nutzung',
    chatGptPrimaryLimit: 'Primäres Limit',
    chatGptSecondaryLimit: 'Sekundäres Limit',
    chatGptUsagePercent: '{percent} % verwendet',
    chatGptResetsAt: 'Zurücksetzung um {time}',
    chatGptRateLimited: 'Nutzungslimit erreicht',
    chatGptOperationFailed: 'Der Vorgang ist fehlgeschlagen. Versuchen Sie es erneut.',
  },
  es: {
    setSecAiProvider: 'Proveedor de IA',
    onbLocalAi: 'NiuOffice AI funciona con OpenAI Endpoint o ChatGPT',
    onbNote3:
      'Usa un servidor OpenAI Endpoint en ejecución o inicia sesión con tu suscripción de ChatGPT.',
    aiProviderChoose: 'Elige cómo se conecta NiuOffice AI.',
    aiProviderLmStudioHint: 'Servidor compatible con OpenAI autenticado con clave API Bearer',
    aiProviderChatGptHint: 'Usar tu suscripción de ChatGPT',
    aiProviderOpenSettings: 'Abrir ajustes del proveedor de IA',
    chatGptConnectedPlan: 'Conectado · {plan}',
    chatGptSignedOut: 'Es necesario iniciar sesión',
    chatGptUnavailable: 'Conexión con ChatGPT no disponible',
    chatGptDescription:
      'Inicia sesión de forma segura en el navegador para usar tu plan de ChatGPT.',
    chatGptSignIn: 'Iniciar sesión con ChatGPT',
    chatGptSigningIn: 'Esperando el inicio de sesión en el navegador…',
    chatGptSignOut: 'Cerrar sesión',
    chatGptAccount: 'Cuenta',
    chatGptPlan: 'Plan',
    chatGptUsage: 'Uso',
    chatGptPrimaryLimit: 'Límite principal',
    chatGptSecondaryLimit: 'Límite secundario',
    chatGptUsagePercent: '{percent} % usado',
    chatGptResetsAt: 'Se restablece a las {time}',
    chatGptRateLimited: 'Se alcanzó el límite de uso',
    chatGptOperationFailed: 'La operación falló. Inténtalo de nuevo.',
  },
  th: {
    setSecAiProvider: 'ผู้ให้บริการ AI',
    onbLocalAi: 'NiuOffice AI ใช้งานได้กับ OpenAI Endpoint หรือ ChatGPT',
    onbNote3:
      'ใช้เซิร์ฟเวอร์ OpenAI Endpoint ที่กำลังทำงาน หรือเข้าสู่ระบบด้วยการสมัครสมาชิก ChatGPT',
    aiProviderChoose: 'เลือกวิธีเชื่อมต่อ NiuOffice AI',
    aiProviderLmStudioHint: 'เซิร์ฟเวอร์ที่รองรับ OpenAI พร้อมคีย์ API แบบ Bearer',
    aiProviderChatGptHint: 'ใช้การสมัครสมาชิก ChatGPT ของคุณ',
    aiProviderOpenSettings: 'เปิดการตั้งค่าผู้ให้บริการ AI',
    chatGptConnectedPlan: 'เชื่อมต่อแล้ว · {plan}',
    chatGptSignedOut: 'ต้องเข้าสู่ระบบ',
    chatGptUnavailable: 'การเชื่อมต่อ ChatGPT ไม่พร้อมใช้งาน',
    chatGptDescription: 'เข้าสู่ระบบอย่างปลอดภัยในเบราว์เซอร์เพื่อใช้แผน ChatGPT ของคุณ',
    chatGptSignIn: 'เข้าสู่ระบบด้วย ChatGPT',
    chatGptSigningIn: 'กำลังรอการเข้าสู่ระบบในเบราว์เซอร์…',
    chatGptSignOut: 'ออกจากระบบ',
    chatGptAccount: 'บัญชี',
    chatGptPlan: 'แผน',
    chatGptUsage: 'การใช้งาน',
    chatGptPrimaryLimit: 'ขีดจำกัดหลัก',
    chatGptSecondaryLimit: 'ขีดจำกัดรอง',
    chatGptUsagePercent: 'ใช้ไป {percent}%',
    chatGptResetsAt: 'รีเซ็ตเวลา {time}',
    chatGptRateLimited: 'ถึงขีดจำกัดการใช้งานแล้ว',
    chatGptOperationFailed: 'การดำเนินการล้มเหลว โปรดลองอีกครั้ง',
  },
  id: {
    setSecAiProvider: 'Penyedia AI',
    onbLocalAi: 'NiuOffice AI bekerja dengan OpenAI Endpoint atau ChatGPT',
    onbNote3: 'Gunakan server OpenAI Endpoint yang aktif atau masuk dengan langganan ChatGPT Anda.',
    aiProviderChoose: 'Pilih cara NiuOffice AI terhubung.',
    aiProviderLmStudioHint: 'Server kompatibel OpenAI dengan kunci API Bearer',
    aiProviderChatGptHint: 'Gunakan langganan ChatGPT Anda',
    aiProviderOpenSettings: 'Buka pengaturan penyedia AI',
    chatGptConnectedPlan: 'Terhubung · {plan}',
    chatGptSignedOut: 'Harus masuk',
    chatGptUnavailable: 'Koneksi ChatGPT tidak tersedia',
    chatGptDescription: 'Masuk dengan aman di browser untuk menggunakan paket ChatGPT Anda.',
    chatGptSignIn: 'Masuk dengan ChatGPT',
    chatGptSigningIn: 'Menunggu masuk melalui browser…',
    chatGptSignOut: 'Keluar',
    chatGptAccount: 'Akun',
    chatGptPlan: 'Paket',
    chatGptUsage: 'Penggunaan',
    chatGptPrimaryLimit: 'Batas utama',
    chatGptSecondaryLimit: 'Batas sekunder',
    chatGptUsagePercent: '{percent}% digunakan',
    chatGptResetsAt: 'Direset {time}',
    chatGptRateLimited: 'Batas penggunaan tercapai',
    chatGptOperationFailed: 'Operasi gagal. Coba lagi.',
  },
  ru: {
    setSecAiProvider: 'Поставщик ИИ',
    onbLocalAi: 'NiuOffice AI работает с OpenAI Endpoint или ChatGPT',
    onbNote3: 'Используйте запущенный сервер OpenAI Endpoint или войдите с подпиской ChatGPT.',
    aiProviderChoose: 'Выберите способ подключения NiuOffice AI.',
    aiProviderLmStudioHint: 'OpenAI-совместимый сервер с API-ключом Bearer',
    aiProviderChatGptHint: 'Использовать подписку ChatGPT',
    aiProviderOpenSettings: 'Открыть настройки поставщика ИИ',
    chatGptConnectedPlan: 'Подключено · {plan}',
    chatGptSignedOut: 'Требуется вход',
    chatGptUnavailable: 'Подключение к ChatGPT недоступно',
    chatGptDescription: 'Безопасно войдите в браузере, чтобы использовать свой тариф ChatGPT.',
    chatGptSignIn: 'Войти через ChatGPT',
    chatGptSigningIn: 'Ожидание входа в браузере…',
    chatGptSignOut: 'Выйти',
    chatGptAccount: 'Аккаунт',
    chatGptPlan: 'Тариф',
    chatGptUsage: 'Использование',
    chatGptPrimaryLimit: 'Основной лимит',
    chatGptSecondaryLimit: 'Дополнительный лимит',
    chatGptUsagePercent: 'Использовано {percent} %',
    chatGptResetsAt: 'Сброс в {time}',
    chatGptRateLimited: 'Достигнут лимит использования',
    chatGptOperationFailed: 'Не удалось выполнить операцию. Повторите попытку.',
  },
  ar: {
    setSecAiProvider: 'موفّر الذكاء الاصطناعي',
    onbLocalAi: 'يعمل NiuOffice AI مع OpenAI Endpoint أو ChatGPT',
    onbNote3: 'استخدم خادم OpenAI Endpoint قيد التشغيل أو سجّل الدخول باشتراك ChatGPT.',
    aiProviderChoose: 'اختر كيفية اتصال NiuOffice AI.',
    aiProviderLmStudioHint: 'خادم متوافق مع OpenAI ومفتاح API من نوع Bearer',
    aiProviderChatGptHint: 'استخدام اشتراك ChatGPT',
    aiProviderOpenSettings: 'فتح إعدادات موفّر الذكاء الاصطناعي',
    chatGptConnectedPlan: 'متصل · {plan}',
    chatGptSignedOut: 'تسجيل الدخول مطلوب',
    chatGptUnavailable: 'اتصال ChatGPT غير متاح',
    chatGptDescription: 'سجّل الدخول بأمان في المتصفح لاستخدام خطة ChatGPT الخاصة بك.',
    chatGptSignIn: 'تسجيل الدخول باستخدام ChatGPT',
    chatGptSigningIn: 'بانتظار تسجيل الدخول في المتصفح…',
    chatGptSignOut: 'تسجيل الخروج',
    chatGptAccount: 'الحساب',
    chatGptPlan: 'الخطة',
    chatGptUsage: 'الاستخدام',
    chatGptPrimaryLimit: 'الحد الأساسي',
    chatGptSecondaryLimit: 'الحد الثانوي',
    chatGptUsagePercent: 'تم استخدام {percent}٪',
    chatGptResetsAt: 'إعادة التعيين في {time}',
    chatGptRateLimited: 'تم بلوغ حد الاستخدام',
    chatGptOperationFailed: 'فشلت العملية. يُرجى المحاولة مجددًا.',
  },
  pt: {
    setSecAiProvider: 'Provedor de IA',
    onbLocalAi: 'O NiuOffice AI funciona com OpenAI Endpoint ou ChatGPT',
    onbNote3: 'Use um servidor OpenAI Endpoint em execução ou entre com sua assinatura do ChatGPT.',
    aiProviderChoose: 'Escolha como o NiuOffice AI se conecta.',
    aiProviderLmStudioHint: 'Servidor compatível com OpenAI autenticado por chave API Bearer',
    aiProviderChatGptHint: 'Usar sua assinatura do ChatGPT',
    aiProviderOpenSettings: 'Abrir configurações do provedor de IA',
    chatGptConnectedPlan: 'Conectado · {plan}',
    chatGptSignedOut: 'É necessário entrar',
    chatGptUnavailable: 'Conexão com o ChatGPT indisponível',
    chatGptDescription: 'Entre com segurança no navegador para usar seu plano do ChatGPT.',
    chatGptSignIn: 'Entrar com o ChatGPT',
    chatGptSigningIn: 'Aguardando entrada pelo navegador…',
    chatGptSignOut: 'Sair',
    chatGptAccount: 'Conta',
    chatGptPlan: 'Plano',
    chatGptUsage: 'Uso',
    chatGptPrimaryLimit: 'Limite principal',
    chatGptSecondaryLimit: 'Limite secundário',
    chatGptUsagePercent: '{percent}% usado',
    chatGptResetsAt: 'Redefine às {time}',
    chatGptRateLimited: 'Limite de uso atingido',
    chatGptOperationFailed: 'A operação falhou. Tente novamente.',
  },
  it: {
    setSecAiProvider: 'Provider IA',
    onbLocalAi: 'NiuOffice AI funziona con OpenAI Endpoint o ChatGPT',
    onbNote3: 'Usa un server OpenAI Endpoint attivo oppure accedi con il tuo abbonamento ChatGPT.',
    aiProviderChoose: 'Scegli come si connette NiuOffice AI.',
    aiProviderLmStudioHint: 'Server compatibile con OpenAI autenticato con chiave API Bearer',
    aiProviderChatGptHint: 'Usa il tuo abbonamento ChatGPT',
    aiProviderOpenSettings: 'Apri impostazioni provider IA',
    chatGptConnectedPlan: 'Connesso · {plan}',
    chatGptSignedOut: 'Accesso richiesto',
    chatGptUnavailable: 'Connessione a ChatGPT non disponibile',
    chatGptDescription: 'Accedi in modo sicuro nel browser per usare il tuo piano ChatGPT.',
    chatGptSignIn: 'Accedi con ChatGPT',
    chatGptSigningIn: 'In attesa dell’accesso nel browser…',
    chatGptSignOut: 'Esci',
    chatGptAccount: 'Account',
    chatGptPlan: 'Piano',
    chatGptUsage: 'Utilizzo',
    chatGptPrimaryLimit: 'Limite principale',
    chatGptSecondaryLimit: 'Limite secondario',
    chatGptUsagePercent: '{percent}% utilizzato',
    chatGptResetsAt: 'Ripristino alle {time}',
    chatGptRateLimited: 'Limite di utilizzo raggiunto',
    chatGptOperationFailed: 'Operazione non riuscita. Riprova.',
  },
  pl: {
    setSecAiProvider: 'Dostawca AI',
    onbLocalAi: 'NiuOffice AI działa z OpenAI Endpoint lub ChatGPT',
    onbNote3: 'Użyj uruchomionego serwera OpenAI Endpoint albo zaloguj się subskrypcją ChatGPT.',
    aiProviderChoose: 'Wybierz sposób połączenia NiuOffice AI.',
    aiProviderLmStudioHint: 'Serwer zgodny z OpenAI uwierzytelniany kluczem API Bearer',
    aiProviderChatGptHint: 'Użyj subskrypcji ChatGPT',
    aiProviderOpenSettings: 'Otwórz ustawienia dostawcy AI',
    chatGptConnectedPlan: 'Połączono · {plan}',
    chatGptSignedOut: 'Wymagane logowanie',
    chatGptUnavailable: 'Połączenie z ChatGPT jest niedostępne',
    chatGptDescription: 'Zaloguj się bezpiecznie w przeglądarce, aby używać planu ChatGPT.',
    chatGptSignIn: 'Zaloguj się przez ChatGPT',
    chatGptSigningIn: 'Oczekiwanie na logowanie w przeglądarce…',
    chatGptSignOut: 'Wyloguj się',
    chatGptAccount: 'Konto',
    chatGptPlan: 'Plan',
    chatGptUsage: 'Użycie',
    chatGptPrimaryLimit: 'Limit główny',
    chatGptSecondaryLimit: 'Limit dodatkowy',
    chatGptUsagePercent: 'Wykorzystano {percent}%',
    chatGptResetsAt: 'Reset o {time}',
    chatGptRateLimited: 'Osiągnięto limit użycia',
    chatGptOperationFailed: 'Operacja nie powiodła się. Spróbuj ponownie.',
  },
  nl: {
    setSecAiProvider: 'AI-provider',
    onbLocalAi: 'NiuOffice AI werkt met OpenAI Endpoint of ChatGPT',
    onbNote3:
      'Gebruik een actieve OpenAI Endpoint-server of meld je aan met je ChatGPT-abonnement.',
    aiProviderChoose: 'Kies hoe NiuOffice AI verbinding maakt.',
    aiProviderLmStudioHint: 'OpenAI-compatibele server met een Bearer API-sleutel',
    aiProviderChatGptHint: 'Gebruik je ChatGPT-abonnement',
    aiProviderOpenSettings: 'Instellingen van AI-provider openen',
    chatGptConnectedPlan: 'Verbonden · {plan}',
    chatGptSignedOut: 'Aanmelden vereist',
    chatGptUnavailable: 'ChatGPT-verbinding niet beschikbaar',
    chatGptDescription: 'Meld je veilig aan in de browser om je ChatGPT-abonnement te gebruiken.',
    chatGptSignIn: 'Aanmelden met ChatGPT',
    chatGptSigningIn: 'Wachten op aanmelden in de browser…',
    chatGptSignOut: 'Afmelden',
    chatGptAccount: 'Account',
    chatGptPlan: 'Abonnement',
    chatGptUsage: 'Gebruik',
    chatGptPrimaryLimit: 'Primaire limiet',
    chatGptSecondaryLimit: 'Secundaire limiet',
    chatGptUsagePercent: '{percent}% gebruikt',
    chatGptResetsAt: 'Wordt om {time} gereset',
    chatGptRateLimited: 'Gebruikslimiet bereikt',
    chatGptOperationFailed: 'De bewerking is mislukt. Probeer het opnieuw.',
  },
  ms: {
    setSecAiProvider: 'Penyedia AI',
    onbLocalAi: 'NiuOffice AI berfungsi dengan OpenAI Endpoint atau ChatGPT',
    onbNote3:
      'Gunakan pelayan OpenAI Endpoint yang sedang berjalan atau log masuk dengan langganan ChatGPT anda.',
    aiProviderChoose: 'Pilih cara NiuOffice AI bersambung.',
    aiProviderLmStudioHint: 'Pelayan serasi OpenAI dengan kunci API Bearer',
    aiProviderChatGptHint: 'Gunakan langganan ChatGPT anda',
    aiProviderOpenSettings: 'Buka tetapan penyedia AI',
    chatGptConnectedPlan: 'Disambungkan · {plan}',
    chatGptSignedOut: 'Log masuk diperlukan',
    chatGptUnavailable: 'Sambungan ChatGPT tidak tersedia',
    chatGptDescription:
      'Log masuk dengan selamat dalam pelayar untuk menggunakan pelan ChatGPT anda.',
    chatGptSignIn: 'Log masuk dengan ChatGPT',
    chatGptSigningIn: 'Menunggu log masuk dalam pelayar…',
    chatGptSignOut: 'Log keluar',
    chatGptAccount: 'Akaun',
    chatGptPlan: 'Pelan',
    chatGptUsage: 'Penggunaan',
    chatGptPrimaryLimit: 'Had utama',
    chatGptSecondaryLimit: 'Had sekunder',
    chatGptUsagePercent: '{percent}% digunakan',
    chatGptResetsAt: 'Ditetapkan semula pada {time}',
    chatGptRateLimited: 'Had penggunaan dicapai',
    chatGptOperationFailed: 'Operasi gagal. Sila cuba lagi.',
  },
  he: {
    setSecAiProvider: 'ספק AI',
    onbLocalAi: 'NiuOffice AI פועל עם OpenAI Endpoint או ChatGPT',
    onbNote3: 'השתמשו בשרת OpenAI Endpoint פעיל או היכנסו באמצעות מינוי ChatGPT.',
    aiProviderChoose: 'בחרו כיצד NiuOffice AI יתחבר.',
    aiProviderLmStudioHint: 'שרת תואם OpenAI עם מפתח API מסוג Bearer',
    aiProviderChatGptHint: 'שימוש במינוי ChatGPT שלך',
    aiProviderOpenSettings: 'פתיחת הגדרות ספק AI',
    chatGptConnectedPlan: 'מחובר · {plan}',
    chatGptSignedOut: 'נדרשת כניסה',
    chatGptUnavailable: 'החיבור ל-ChatGPT אינו זמין',
    chatGptDescription: 'יש להיכנס באופן מאובטח בדפדפן כדי להשתמש בתוכנית ChatGPT שלך.',
    chatGptSignIn: 'כניסה באמצעות ChatGPT',
    chatGptSigningIn: 'ממתין לכניסה בדפדפן…',
    chatGptSignOut: 'יציאה',
    chatGptAccount: 'חשבון',
    chatGptPlan: 'תוכנית',
    chatGptUsage: 'שימוש',
    chatGptPrimaryLimit: 'מגבלה ראשית',
    chatGptSecondaryLimit: 'מגבלה משנית',
    chatGptUsagePercent: 'נעשה שימוש ב-{percent}%',
    chatGptResetsAt: 'איפוס בשעה {time}',
    chatGptRateLimited: 'הגעת למגבלת השימוש',
    chatGptOperationFailed: 'הפעולה נכשלה. נסו שוב.',
  },
  hi: {
    setSecAiProvider: 'AI प्रदाता',
    onbLocalAi: 'NiuOffice AI, OpenAI Endpoint या ChatGPT के साथ काम करता है',
    onbNote3: 'चल रहे OpenAI Endpoint सर्वर का उपयोग करें या अपनी ChatGPT सदस्यता से साइन इन करें।',
    aiProviderChoose: 'चुनें कि NiuOffice AI कैसे कनेक्ट हो।',
    aiProviderLmStudioHint: 'Bearer API कुंजी वाला OpenAI-संगत सर्वर',
    aiProviderChatGptHint: 'अपनी ChatGPT सदस्यता का उपयोग करें',
    aiProviderOpenSettings: 'AI प्रदाता सेटिंग खोलें',
    chatGptConnectedPlan: 'कनेक्टेड · {plan}',
    chatGptSignedOut: 'साइन इन आवश्यक है',
    chatGptUnavailable: 'ChatGPT कनेक्शन उपलब्ध नहीं है',
    chatGptDescription:
      'अपने ChatGPT प्लान का उपयोग करने के लिए ब्राउज़र में सुरक्षित रूप से साइन इन करें।',
    chatGptSignIn: 'ChatGPT से साइन इन करें',
    chatGptSigningIn: 'ब्राउज़र साइन-इन की प्रतीक्षा हो रही है…',
    chatGptSignOut: 'साइन आउट',
    chatGptAccount: 'खाता',
    chatGptPlan: 'प्लान',
    chatGptUsage: 'उपयोग',
    chatGptPrimaryLimit: 'प्राथमिक सीमा',
    chatGptSecondaryLimit: 'द्वितीयक सीमा',
    chatGptUsagePercent: '{percent}% उपयोग हुआ',
    chatGptResetsAt: '{time} पर रीसेट',
    chatGptRateLimited: 'उपयोग सीमा पूरी हो गई',
    chatGptOperationFailed: 'कार्रवाई विफल रही। फिर से कोशिश करें।',
  },
  'zh-TW': {
    setSecAiProvider: 'AI 提供者',
    onbLocalAi: 'NiuOffice AI 可搭配 OpenAI Endpoint 或 ChatGPT 使用',
    onbNote3: '使用正在執行的 OpenAI Endpoint 伺服器，或登入您的 ChatGPT 訂閱方案。',
    aiProviderChoose: '選擇 NiuOffice AI 的連線方式。',
    aiProviderLmStudioHint: '使用 Bearer API 金鑰的 OpenAI 相容伺服器',
    aiProviderChatGptHint: '使用您的 ChatGPT 訂閱方案',
    aiProviderOpenSettings: '開啟 AI 提供者設定',
    chatGptConnectedPlan: '已連線 · {plan}',
    chatGptSignedOut: '需要登入',
    chatGptUnavailable: 'ChatGPT 連線無法使用',
    chatGptDescription: '在瀏覽器中安全登入，以使用您的 ChatGPT 方案。',
    chatGptSignIn: '使用 ChatGPT 登入',
    chatGptSigningIn: '正在等待瀏覽器登入…',
    chatGptSignOut: '登出',
    chatGptAccount: '帳戶',
    chatGptPlan: '方案',
    chatGptUsage: '使用量',
    chatGptPrimaryLimit: '主要限制',
    chatGptSecondaryLimit: '次要限制',
    chatGptUsagePercent: '已使用 {percent}%',
    chatGptResetsAt: '{time} 重設',
    chatGptRateLimited: '已達使用上限',
    chatGptOperationFailed: '操作失敗，請再試一次。',
  },
} as const
