/** Strings introduced by the LM Studio provider selector. */
export const aiProviderStrings = {
  zh: {
    setSecAiProvider: 'AI 提供商',
    onbLocalAi: 'BP-Office AI 可使用 LM Studio',
    onbNote3: '使用正在运行的 LM Studio 服务器。',
    aiProviderChoose: '选择 BP-Office AI 的连接方式。',
    aiProviderLmStudioHint: '在此设备上运行的私有本地 AI',
    aiProviderOpenSettings: '打开 AI 提供商设置',
  },
  en: {
    setSecAiProvider: 'AI Provider',
    onbLocalAi: 'BP-Office AI works with LM Studio',
    onbNote3: 'Use a running LM Studio server.',
    aiProviderChoose: 'Choose how BP-Office AI connects.',
    aiProviderLmStudioHint: 'Private local AI running on this device',
    aiProviderOpenSettings: 'Open AI provider settings',
  },
  ja: {
    setSecAiProvider: 'AI プロバイダー',
    onbLocalAi: 'BP-Office AI は LM Studio で利用できます',
    onbNote3: '実行中の LM Studio サーバーを使用してください。',
    aiProviderChoose: 'BP-Office AI の接続方法を選択します。',
    aiProviderLmStudioHint: 'このデバイスで動作するプライベートなローカル AI',
    aiProviderOpenSettings: 'AI プロバイダー設定を開く',
  },
  ko: {
    setSecAiProvider: 'AI 공급자',
    onbLocalAi: 'BP-Office AI는 LM Studio와 함께 작동합니다',
    onbNote3: '실행 중인 LM Studio 서버를 사용하세요.',
    aiProviderChoose: 'BP-Office AI 연결 방식을 선택하세요.',
    aiProviderLmStudioHint: '이 기기에서 실행되는 비공개 로컬 AI',
    aiProviderOpenSettings: 'AI 공급자 설정 열기',
  },
  fr: {
    setSecAiProvider: 'Fournisseur d’IA',
    onbLocalAi: 'BP-Office AI fonctionne avec LM Studio',
    onbNote3: 'Utilisez un serveur LM Studio actif.',
    aiProviderChoose: 'Choisissez comment BP-Office AI se connecte.',
    aiProviderLmStudioHint: 'IA locale privée exécutée sur cet appareil',
    aiProviderOpenSettings: 'Ouvrir les réglages du fournisseur d’IA',
  },
  de: {
    setSecAiProvider: 'KI-Anbieter',
    onbLocalAi: 'BP-Office AI funktioniert mit LM Studio',
    onbNote3: 'Verwenden Sie einen laufenden LM Studio-Server.',
    aiProviderChoose: 'Wählen Sie, wie BP-Office AI eine Verbindung herstellt.',
    aiProviderLmStudioHint: 'Private lokale KI auf diesem Gerät',
    aiProviderOpenSettings: 'KI-Anbietereinstellungen öffnen',
  },
  es: {
    setSecAiProvider: 'Proveedor de IA',
    onbLocalAi: 'BP-Office AI funciona con LM Studio',
    onbNote3: 'Usa un servidor LM Studio en ejecución.',
    aiProviderChoose: 'Elige cómo se conecta BP-Office AI.',
    aiProviderLmStudioHint: 'IA local privada ejecutada en este dispositivo',
    aiProviderOpenSettings: 'Abrir ajustes del proveedor de IA',
  },
  th: {
    setSecAiProvider: 'ผู้ให้บริการ AI',
    onbLocalAi: 'BP-Office AI ใช้งานร่วมกับ LM Studio',
    onbNote3: 'ใช้เซิร์ฟเวอร์ LM Studio ที่กำลังทำงาน',
    aiProviderChoose: 'เลือกวิธีเชื่อมต่อ BP-Office AI',
    aiProviderLmStudioHint: 'AI ภายในเครื่องแบบส่วนตัวที่ทำงานบนอุปกรณ์นี้',
    aiProviderOpenSettings: 'เปิดการตั้งค่าผู้ให้บริการ AI',
  },
  id: {
    setSecAiProvider: 'Penyedia AI',
    onbLocalAi: 'BP-Office AI bekerja dengan LM Studio',
    onbNote3: 'Gunakan server LM Studio yang aktif.',
    aiProviderChoose: 'Pilih cara BP-Office AI terhubung.',
    aiProviderLmStudioHint: 'AI lokal privat yang berjalan di perangkat ini',
    aiProviderOpenSettings: 'Buka pengaturan penyedia AI',
  },
  ru: {
    setSecAiProvider: 'Поставщик ИИ',
    onbLocalAi: 'BP-Office AI работает с LM Studio',
    onbNote3: 'Используйте запущенный сервер LM Studio.',
    aiProviderChoose: 'Выберите способ подключения BP-Office AI.',
    aiProviderLmStudioHint: 'Приватный локальный ИИ на этом устройстве',
    aiProviderOpenSettings: 'Открыть настройки поставщика ИИ',
  },
  ar: {
    setSecAiProvider: 'موفّر الذكاء الاصطناعي',
    onbLocalAi: 'يعمل BP-Office AI مع LM Studio',
    onbNote3: 'استخدم خادم LM Studio قيد التشغيل.',
    aiProviderChoose: 'اختر كيفية اتصال BP-Office AI.',
    aiProviderLmStudioHint: 'ذكاء اصطناعي محلي خاص يعمل على هذا الجهاز',
    aiProviderOpenSettings: 'فتح إعدادات موفّر الذكاء الاصطناعي',
  },
  pt: {
    setSecAiProvider: 'Provedor de IA',
    onbLocalAi: 'O BP-Office AI funciona com LM Studio',
    onbNote3: 'Use um servidor LM Studio em execução.',
    aiProviderChoose: 'Escolha como o BP-Office AI se conecta.',
    aiProviderLmStudioHint: 'IA local privada executada neste dispositivo',
    aiProviderOpenSettings: 'Abrir configurações do provedor de IA',
  },
  it: {
    setSecAiProvider: 'Provider IA',
    onbLocalAi: 'BP-Office AI funziona con LM Studio',
    onbNote3: 'Usa un server LM Studio attivo.',
    aiProviderChoose: 'Scegli come si connette BP-Office AI.',
    aiProviderLmStudioHint: 'IA locale privata in esecuzione su questo dispositivo',
    aiProviderOpenSettings: 'Apri impostazioni provider IA',
  },
  pl: {
    setSecAiProvider: 'Dostawca AI',
    onbLocalAi: 'BP-Office AI działa z LM Studio',
    onbNote3: 'Użyj uruchomionego serwera LM Studio.',
    aiProviderChoose: 'Wybierz sposób połączenia BP-Office AI.',
    aiProviderLmStudioHint: 'Prywatna lokalna AI działająca na tym urządzeniu',
    aiProviderOpenSettings: 'Otwórz ustawienia dostawcy AI',
  },
  nl: {
    setSecAiProvider: 'AI-provider',
    onbLocalAi: 'BP-Office AI werkt met LM Studio',
    onbNote3: 'Gebruik een actieve LM Studio-server.',
    aiProviderChoose: 'Kies hoe BP-Office AI verbinding maakt.',
    aiProviderLmStudioHint: 'Privé lokale AI die op dit apparaat draait',
    aiProviderOpenSettings: 'Instellingen van AI-provider openen',
  },
  ms: {
    setSecAiProvider: 'Penyedia AI',
    onbLocalAi: 'BP-Office AI berfungsi dengan LM Studio',
    onbNote3: 'Gunakan pelayan LM Studio yang sedang berjalan.',
    aiProviderChoose: 'Pilih cara BP-Office AI bersambung.',
    aiProviderLmStudioHint: 'AI setempat peribadi yang berjalan pada peranti ini',
    aiProviderOpenSettings: 'Buka tetapan penyedia AI',
  },
  he: {
    setSecAiProvider: 'ספק AI',
    onbLocalAi: 'BP-Office AI פועל עם LM Studio',
    onbNote3: 'השתמשו בשרת LM Studio פעיל.',
    aiProviderChoose: 'בחרו כיצד BP-Office AI יתחבר.',
    aiProviderLmStudioHint: 'AI מקומי ופרטי שפועל במכשיר זה',
    aiProviderOpenSettings: 'פתיחת הגדרות ספק AI',
  },
  hi: {
    setSecAiProvider: 'AI प्रदाता',
    onbLocalAi: 'BP-Office AI, LM Studio के साथ काम करता है',
    onbNote3: 'चल रहे LM Studio सर्वर का उपयोग करें।',
    aiProviderChoose: 'चुनें कि BP-Office AI कैसे कनेक्ट हो।',
    aiProviderLmStudioHint: 'इस डिवाइस पर चलने वाला निजी स्थानीय AI',
    aiProviderOpenSettings: 'AI प्रदाता सेटिंग खोलें',
  },
  'zh-TW': {
    setSecAiProvider: 'AI 提供者',
    onbLocalAi: 'BP-Office AI 可搭配 LM Studio 使用',
    onbNote3: '使用正在執行的 LM Studio 伺服器。',
    aiProviderChoose: '選擇 BP-Office AI 的連線方式。',
    aiProviderLmStudioHint: '在此裝置上執行的私密本機 AI',
    aiProviderOpenSettings: '開啟 AI 提供者設定',
  },
} as const
