export const homeInterfaceStrings = {
  zh: {
    newHtml: 'AI HTML',
    newPdf: 'AI PDF',
    removeFolderRoot: '从列表移除',
    addFolderRoot: '添加文件夹…',
    rootUnavailable: '不可用',
    cloudSortRecent: '最近',
    cloudSortOldest: '最早',
    aiFontSizeDefault: '默认',
    aiFontSizeLarge: '大',
    aiFontSizeXLarge: '特大',
    aiFontSizeCustom: '自定义',
    aiPanelSideLeft: '左侧',
    aiPanelSideRight: '右侧',
    setAiPanelSide: 'AI 侧边栏位置',
    setAiFontSize: 'AI 面板文字大小',
    setAiSpellcheck: 'AI 对话拼写检查',
    setAiSpellcheckDesc: '在 AI 对话输入框中输入时标出拼写错误的单词。',
    setDefaultApp: '设为 Office 文档默认程序',
    setDefaultAppFailed: '设置失败，请在系统设置中手动更改。',
    setDefaultAppIs: 'BP Office 已是默认程序。',
    setDefaultAppOther: '当前默认程序：{app}',
    setDefaultAppDesc: '双击 .docx、.xlsx、.pdf 文件时用 BP Office 打开。',
    setDefaultAppOpenSettings: '打开系统设置',
    setDefaultAppSet: '设为默认',
  },
  en: {
    newHtml: 'AI HTML',
    newPdf: 'AI PDF',
    removeFolderRoot: 'Remove from list',
    addFolderRoot: 'Add folder…',
    rootUnavailable: 'Not available',
    cloudSortRecent: 'Recent',
    cloudSortOldest: 'Oldest',
    aiFontSizeDefault: 'Default',
    aiFontSizeLarge: 'Large',
    aiFontSizeXLarge: 'Extra large',
    aiFontSizeCustom: 'Custom',
    aiPanelSideLeft: 'Left',
    aiPanelSideRight: 'Right',
    setAiPanelSide: 'AI sidebar position',
    setAiFontSize: 'AI panel text size',
    setAiSpellcheck: 'Spell check in AI chat',
    setAiSpellcheckDesc: 'Underline misspelled words while typing in the AI chat input.',
    setDefaultApp: 'Default app for Office documents',
    setDefaultAppFailed: 'Could not change it. Please set it in the system settings.',
    setDefaultAppIs: 'BP Office is already the default.',
    setDefaultAppOther: 'Current default: {app}',
    setDefaultAppDesc: 'Open .docx, .xlsx and .pdf files in BP Office when double-clicked.',
    setDefaultAppOpenSettings: 'Open system settings',
    setDefaultAppSet: 'Make default',
  },
  ja: {
    newHtml: 'AI HTML',
    newPdf: 'AI PDF',
    removeFolderRoot: 'リストから削除',
    addFolderRoot: 'フォルダーを追加…',
    rootUnavailable: '利用不可',
    cloudSortRecent: '新しい順',
    cloudSortOldest: '古い順',
    aiFontSizeDefault: '標準',
    aiFontSizeLarge: '大',
    aiFontSizeXLarge: '特大',
    aiFontSizeCustom: 'カスタム',
    aiPanelSideLeft: '左側',
    aiPanelSideRight: '右側',
    setAiPanelSide: 'AI サイドバーの位置',
    setAiFontSize: 'AI パネルの文字サイズ',
    setAiSpellcheck: 'AI チャットのスペルチェック',
    setAiSpellcheckDesc: 'AI チャットの入力欄で入力中にスペルミスの単語に下線を表示します。',
    setDefaultApp: 'Office 文書の既定のアプリ',
    setDefaultAppFailed: '変更できませんでした。システム設定で設定してください。',
    setDefaultAppIs: 'BP Office はすでに既定のアプリです。',
    setDefaultAppOther: '現在の既定：{app}',
    setDefaultAppDesc: '.docx、.xlsx、.pdf ファイルをダブルクリックしたとき BP Office で開きます。',
    setDefaultAppOpenSettings: 'システム設定を開く',
    setDefaultAppSet: '既定にする',
  },
  ko: {
    newHtml: 'AI HTML',
    newPdf: 'AI PDF',
    removeFolderRoot: '목록에서 제거',
    addFolderRoot: '폴더 추가…',
    rootUnavailable: '사용할 수 없음',
    cloudSortRecent: '최신순',
    cloudSortOldest: '오래된순',
    aiFontSizeDefault: '기본',
    aiFontSizeLarge: '크게',
    aiFontSizeXLarge: '더 크게',
    aiFontSizeCustom: '사용자 지정',
    aiPanelSideLeft: '왼쪽',
    aiPanelSideRight: '오른쪽',
    setAiPanelSide: 'AI 사이드바 위치',
    setAiFontSize: 'AI 패널 글자 크기',
    setAiSpellcheck: 'AI 채팅 맞춤법 검사',
    setAiSpellcheckDesc: 'AI 채팅 입력란에 입력할 때 잘못된 단어에 밑줄을 표시합니다.',
    setDefaultApp: 'Office 문서 기본 앱',
    setDefaultAppFailed: '변경할 수 없습니다. 시스템 설정에서 직접 설정해 주세요.',
    setDefaultAppIs: 'BP Office가 이미 기본 앱입니다.',
    setDefaultAppOther: '현재 기본 앱: {app}',
    setDefaultAppDesc: '.docx, .xlsx, .pdf 파일을 두 번 클릭하면 BP Office로 엽니다.',
    setDefaultAppOpenSettings: '시스템 설정 열기',
    setDefaultAppSet: '기본으로 설정',
  },
  fr: {
    newHtml: 'AI HTML',
    newPdf: 'AI PDF',
    removeFolderRoot: 'Retirer de la liste',
    addFolderRoot: 'Ajouter un dossier…',
    rootUnavailable: 'Indisponible',
    cloudSortRecent: 'Récents',
    cloudSortOldest: 'Plus anciens',
    aiFontSizeDefault: 'Par défaut',
    aiFontSizeLarge: 'Grande',
    aiFontSizeXLarge: 'Très grande',
    aiFontSizeCustom: 'Personnalisé',
    aiPanelSideLeft: 'Gauche',
    aiPanelSideRight: 'Droite',
    setAiPanelSide: 'Position de la barre latérale IA',
    setAiFontSize: 'Taille du texte du panneau IA',
    setAiSpellcheck: 'Correction orthographique dans le chat IA',
    setAiSpellcheckDesc: 'Souligne les mots mal orthographiés pendant la saisie dans le chat IA.',
    setDefaultApp: 'Application par défaut pour les documents Office',
    setDefaultAppFailed: 'Modification impossible. Définissez-la dans les réglages système.',
    setDefaultAppIs: 'BP Office est déjà l’application par défaut.',
    setDefaultAppOther: 'Par défaut actuellement : {app}',
    setDefaultAppDesc: 'Ouvrir les fichiers .docx, .xlsx et .pdf dans BP Office par double-clic.',
    setDefaultAppOpenSettings: 'Ouvrir les réglages système',
    setDefaultAppSet: 'Définir par défaut',
  },
  de: {
    newHtml: 'AI HTML',
    newPdf: 'AI PDF',
    removeFolderRoot: 'Aus der Liste entfernen',
    addFolderRoot: 'Ordner hinzufügen…',
    rootUnavailable: 'Nicht verfügbar',
    cloudSortRecent: 'Neueste',
    cloudSortOldest: 'Älteste',
    aiFontSizeDefault: 'Standard',
    aiFontSizeLarge: 'Groß',
    aiFontSizeXLarge: 'Sehr groß',
    aiFontSizeCustom: 'Benutzerdefiniert',
    aiPanelSideLeft: 'Links',
    aiPanelSideRight: 'Rechts',
    setAiPanelSide: 'Position der KI-Seitenleiste',
    setAiFontSize: 'Textgröße im KI-Bereich',
    setAiSpellcheck: 'Rechtschreibprüfung im KI-Chat',
    setAiSpellcheckDesc:
      'Unterstreicht falsch geschriebene Wörter beim Tippen im KI-Chat-Eingabefeld.',
    setDefaultApp: 'Standard-App für Office-Dokumente',
    setDefaultAppFailed: 'Änderung nicht möglich. Bitte in den Systemeinstellungen festlegen.',
    setDefaultAppIs: 'BP Office ist bereits die Standard-App.',
    setDefaultAppOther: 'Aktueller Standard: {app}',
    setDefaultAppDesc: '.docx-, .xlsx- und .pdf-Dateien per Doppelklick in BP Office öffnen.',
    setDefaultAppOpenSettings: 'Systemeinstellungen öffnen',
    setDefaultAppSet: 'Als Standard festlegen',
  },
  es: {
    newHtml: 'AI HTML',
    newPdf: 'AI PDF',
    removeFolderRoot: 'Quitar de la lista',
    addFolderRoot: 'Añadir carpeta…',
    rootUnavailable: 'No disponible',
    cloudSortRecent: 'Recientes',
    cloudSortOldest: 'Más antiguos',
    aiFontSizeDefault: 'Predeterminado',
    aiFontSizeLarge: 'Grande',
    aiFontSizeXLarge: 'Muy grande',
    aiFontSizeCustom: 'Personalizado',
    aiPanelSideLeft: 'Izquierda',
    aiPanelSideRight: 'Derecha',
    setAiPanelSide: 'Posición de la barra lateral de IA',
    setAiFontSize: 'Tamaño del texto del panel de IA',
    setAiSpellcheck: 'Corrección ortográfica en el chat de IA',
    setAiSpellcheckDesc:
      'Subraya las palabras mal escritas al escribir en el cuadro del chat de IA.',
    setDefaultApp: 'App predeterminada para documentos de Office',
    setDefaultAppFailed: 'No se pudo cambiar. Configúralo en los ajustes del sistema.',
    setDefaultAppIs: 'BP Office ya es la app predeterminada.',
    setDefaultAppOther: 'Predeterminada actual: {app}',
    setDefaultAppDesc: 'Abrir archivos .docx, .xlsx y .pdf en BP Office al hacer doble clic.',
    setDefaultAppOpenSettings: 'Abrir ajustes del sistema',
    setDefaultAppSet: 'Establecer como predeterminada',
  },
  th: {
    newHtml: 'AI HTML',
    newPdf: 'AI PDF',
    removeFolderRoot: 'นำออกจากรายการ',
    addFolderRoot: 'เพิ่มโฟลเดอร์…',
    rootUnavailable: 'ไม่พร้อมใช้งาน',
    cloudSortRecent: 'ล่าสุด',
    cloudSortOldest: 'เก่าสุด',
    aiFontSizeDefault: 'ค่าเริ่มต้น',
    aiFontSizeLarge: 'ใหญ่',
    aiFontSizeXLarge: 'ใหญ่มาก',
    aiFontSizeCustom: 'กำหนดเอง',
    aiPanelSideLeft: 'ซ้าย',
    aiPanelSideRight: 'ขวา',
    setAiPanelSide: 'ตำแหน่งแถบด้านข้าง AI',
    setAiFontSize: 'ขนาดตัวอักษรในแผง AI',
    setAiSpellcheck: 'ตรวจการสะกดในแชท AI',
    setAiSpellcheckDesc: 'ขีดเส้นใต้คำที่สะกดผิดขณะพิมพ์ในช่องแชท AI',
    setDefaultApp: 'แอปเริ่มต้นสำหรับเอกสาร Office',
    setDefaultAppFailed: 'เปลี่ยนไม่สำเร็จ โปรดตั้งค่าในการตั้งค่าระบบ',
    setDefaultAppIs: 'BP Office เป็นแอปเริ่มต้นอยู่แล้ว',
    setDefaultAppOther: 'แอปเริ่มต้นปัจจุบัน: {app}',
    setDefaultAppDesc: 'เปิดไฟล์ .docx, .xlsx และ .pdf ด้วย BP Office เมื่อดับเบิลคลิก',
    setDefaultAppOpenSettings: 'เปิดการตั้งค่าระบบ',
    setDefaultAppSet: 'ตั้งเป็นค่าเริ่มต้น',
  },
  id: {
    newHtml: 'AI HTML',
    newPdf: 'AI PDF',
    removeFolderRoot: 'Hapus dari daftar',
    addFolderRoot: 'Tambah folder…',
    rootUnavailable: 'Tidak tersedia',
    cloudSortRecent: 'Terbaru',
    cloudSortOldest: 'Terlama',
    aiFontSizeDefault: 'Bawaan',
    aiFontSizeLarge: 'Besar',
    aiFontSizeXLarge: 'Sangat besar',
    aiFontSizeCustom: 'Kustom',
    aiPanelSideLeft: 'Kiri',
    aiPanelSideRight: 'Kanan',
    setAiPanelSide: 'Posisi bilah samping AI',
    setAiFontSize: 'Ukuran teks panel AI',
    setAiSpellcheck: 'Pemeriksaan ejaan di obrolan AI',
    setAiSpellcheckDesc: 'Garis bawahi kata yang salah eja saat mengetik di kotak obrolan AI.',
    setDefaultApp: 'Aplikasi default untuk dokumen Office',
    setDefaultAppFailed: 'Tidak dapat mengubahnya. Atur di pengaturan sistem.',
    setDefaultAppIs: 'BP Office sudah menjadi aplikasi default.',
    setDefaultAppOther: 'Default saat ini: {app}',
    setDefaultAppDesc: 'Buka file .docx, .xlsx, dan .pdf di BP Office saat diklik dua kali.',
    setDefaultAppOpenSettings: 'Buka pengaturan sistem',
    setDefaultAppSet: 'Jadikan default',
  },
  ru: {
    newHtml: 'AI HTML',
    newPdf: 'AI PDF',
    removeFolderRoot: 'Убрать из списка',
    addFolderRoot: 'Добавить папку…',
    rootUnavailable: 'Недоступно',
    cloudSortRecent: 'Сначала новые',
    cloudSortOldest: 'Сначала старые',
    aiFontSizeDefault: 'По умолчанию',
    aiFontSizeLarge: 'Крупный',
    aiFontSizeXLarge: 'Очень крупный',
    aiFontSizeCustom: 'Другой',
    aiPanelSideLeft: 'Слева',
    aiPanelSideRight: 'Справа',
    setAiPanelSide: 'Положение боковой панели ИИ',
    setAiFontSize: 'Размер текста панели ИИ',
    setAiSpellcheck: 'Проверка орфографии в чате ИИ',
    setAiSpellcheckDesc: 'Подчёркивать слова с ошибками при вводе в поле чата ИИ.',
    setDefaultApp: 'Приложение по умолчанию для документов Office',
    setDefaultAppFailed: 'Не удалось изменить. Задайте в системных настройках.',
    setDefaultAppIs: 'BP Office уже является приложением по умолчанию.',
    setDefaultAppOther: 'Сейчас по умолчанию: {app}',
    setDefaultAppDesc: 'Открывать файлы .docx, .xlsx и .pdf в BP Office по двойному щелчку.',
    setDefaultAppOpenSettings: 'Открыть системные настройки',
    setDefaultAppSet: 'Сделать по умолчанию',
  },
  ar: {
    newHtml: 'AI HTML',
    newPdf: 'AI PDF',
    removeFolderRoot: 'إزالة من القائمة',
    addFolderRoot: 'إضافة مجلد…',
    rootUnavailable: 'غير متاح',
    cloudSortRecent: 'الأحدث',
    cloudSortOldest: 'الأقدم',
    aiFontSizeDefault: 'افتراضي',
    aiFontSizeLarge: 'كبير',
    aiFontSizeXLarge: 'كبير جدًا',
    aiFontSizeCustom: 'مخصص',
    aiPanelSideLeft: 'اليسار',
    aiPanelSideRight: 'اليمين',
    setAiPanelSide: 'موضع الشريط الجانبي للذكاء الاصطناعي',
    setAiFontSize: 'حجم نص لوحة الذكاء الاصطناعي',
    setAiSpellcheck: 'التدقيق الإملائي في محادثة الذكاء الاصطناعي',
    setAiSpellcheckDesc:
      'وضع خط تحت الكلمات الخاطئة إملائيًا أثناء الكتابة في حقل محادثة الذكاء الاصطناعي.',
    setDefaultApp: 'التطبيق الافتراضي لمستندات Office',
    setDefaultAppFailed: 'تعذّر التغيير. يرجى تعيينه من إعدادات النظام.',
    setDefaultAppIs: 'BP Office هو التطبيق الافتراضي بالفعل.',
    setDefaultAppOther: 'الافتراضي الحالي: {app}',
    setDefaultAppDesc: 'فتح ملفات .docx و.xlsx و.pdf في BP Office عند النقر المزدوج.',
    setDefaultAppOpenSettings: 'فتح إعدادات النظام',
    setDefaultAppSet: 'تعيين كافتراضي',
  },
  pt: {
    newHtml: 'AI HTML',
    newPdf: 'AI PDF',
    removeFolderRoot: 'Remover da lista',
    addFolderRoot: 'Adicionar pasta…',
    rootUnavailable: 'Indisponível',
    cloudSortRecent: 'Recentes',
    cloudSortOldest: 'Mais antigos',
    aiFontSizeDefault: 'Padrão',
    aiFontSizeLarge: 'Grande',
    aiFontSizeXLarge: 'Muito grande',
    aiFontSizeCustom: 'Personalizado',
    aiPanelSideLeft: 'Esquerda',
    aiPanelSideRight: 'Direita',
    setAiPanelSide: 'Posição da barra lateral de IA',
    setAiFontSize: 'Tamanho do texto do painel de IA',
    setAiSpellcheck: 'Verificação ortográfica no chat de IA',
    setAiSpellcheckDesc:
      'Sublinha palavras com erros ortográficos ao digitar na caixa do chat de IA.',
    setDefaultApp: 'App padrão para documentos do Office',
    setDefaultAppFailed: 'Não foi possível alterar. Defina nas configurações do sistema.',
    setDefaultAppIs: 'O BP Office já é o app padrão.',
    setDefaultAppOther: 'Padrão atual: {app}',
    setDefaultAppDesc: 'Abrir arquivos .docx, .xlsx e .pdf no BP Office ao clicar duas vezes.',
    setDefaultAppOpenSettings: 'Abrir configurações do sistema',
    setDefaultAppSet: 'Definir como padrão',
  },
  it: {
    newHtml: 'AI HTML',
    newPdf: 'AI PDF',
    removeFolderRoot: "Rimuovi dall'elenco",
    addFolderRoot: 'Aggiungi cartella…',
    rootUnavailable: 'Non disponibile',
    cloudSortRecent: 'Recenti',
    cloudSortOldest: 'Meno recenti',
    aiFontSizeDefault: 'Predefinita',
    aiFontSizeLarge: 'Grande',
    aiFontSizeXLarge: 'Molto grande',
    aiFontSizeCustom: 'Personalizzato',
    aiPanelSideLeft: 'Sinistra',
    aiPanelSideRight: 'Destra',
    setAiPanelSide: 'Posizione della barra laterale IA',
    setAiFontSize: 'Dimensione del testo del pannello IA',
    setAiSpellcheck: 'Controllo ortografico nella chat IA',
    setAiSpellcheckDesc: 'Sottolinea le parole errate durante la digitazione nella chat IA.',
    setDefaultApp: 'App predefinita per i documenti Office',
    setDefaultAppFailed: 'Impossibile modificare. Impostala nelle impostazioni di sistema.',
    setDefaultAppIs: 'BP Office è già l’app predefinita.',
    setDefaultAppOther: 'Predefinita attuale: {app}',
    setDefaultAppDesc: 'Apri i file .docx, .xlsx e .pdf in BP Office con un doppio clic.',
    setDefaultAppOpenSettings: 'Apri impostazioni di sistema',
    setDefaultAppSet: 'Imposta come predefinita',
  },
  pl: {
    newHtml: 'AI HTML',
    newPdf: 'AI PDF',
    removeFolderRoot: 'Usuń z listy',
    addFolderRoot: 'Dodaj folder…',
    rootUnavailable: 'Niedostępny',
    cloudSortRecent: 'Najnowsze',
    cloudSortOldest: 'Najstarsze',
    aiFontSizeDefault: 'Domyślny',
    aiFontSizeLarge: 'Duży',
    aiFontSizeXLarge: 'Bardzo duży',
    aiFontSizeCustom: 'Niestandardowy',
    aiPanelSideLeft: 'Lewa',
    aiPanelSideRight: 'Prawa',
    setAiPanelSide: 'Położenie panelu bocznego AI',
    setAiFontSize: 'Rozmiar tekstu panelu AI',
    setAiSpellcheck: 'Sprawdzanie pisowni w czacie AI',
    setAiSpellcheckDesc: 'Podkreśla błędnie napisane słowa podczas pisania w polu czatu AI.',
    setDefaultApp: 'Domyślna aplikacja dla dokumentów Office',
    setDefaultAppFailed: 'Nie udało się zmienić. Ustaw w ustawieniach systemu.',
    setDefaultAppIs: 'BP Office jest już aplikacją domyślną.',
    setDefaultAppOther: 'Obecnie domyślna: {app}',
    setDefaultAppDesc: 'Otwieraj pliki .docx, .xlsx i .pdf w BP Office po dwukrotnym kliknięciu.',
    setDefaultAppOpenSettings: 'Otwórz ustawienia systemu',
    setDefaultAppSet: 'Ustaw jako domyślną',
  },
  cs: {
    newHtml: 'AI HTML',
    newPdf: 'AI PDF',
    removeFolderRoot: 'Odebrat ze seznamu',
    addFolderRoot: 'Přidat složku…',
    rootUnavailable: 'Nedostupné',
    cloudSortRecent: 'Nejnovější',
    cloudSortOldest: 'Nejstarší',
    aiFontSizeDefault: 'Výchozí',
    aiFontSizeLarge: 'Velké',
    aiFontSizeXLarge: 'Extra velké',
    aiFontSizeCustom: 'Vlastní',
    aiPanelSideLeft: 'Vlevo',
    aiPanelSideRight: 'Vpravo',
    setAiPanelSide: 'Pozice postranního panelu AI',
    setAiFontSize: 'Velikost textu panelu AI',
    setAiSpellcheck: 'Kontrola pravopisu v chatu AI',
    setAiSpellcheckDesc: 'Podtrhávat překlepy při psaní do vstupního pole chatu AI.',
    setDefaultApp: 'Výchozí aplikace pro dokumenty Office',
    setDefaultAppFailed: 'Změna se nezdařila. Nastavte ji v nastavení systému.',
    setDefaultAppIs: 'BP Office už je výchozí aplikací.',
    setDefaultAppOther: 'Aktuální výchozí: {app}',
    setDefaultAppDesc: 'Otevírat soubory .docx, .xlsx a .pdf v BP Office poklepáním.',
    setDefaultAppOpenSettings: 'Otevřít nastavení systému',
    setDefaultAppSet: 'Nastavit jako výchozí',
  },
  nl: {
    newHtml: 'AI HTML',
    newPdf: 'AI PDF',
    removeFolderRoot: 'Uit lijst verwijderen',
    addFolderRoot: 'Map toevoegen…',
    rootUnavailable: 'Niet beschikbaar',
    cloudSortRecent: 'Recent',
    cloudSortOldest: 'Oudste',
    aiFontSizeDefault: 'Standaard',
    aiFontSizeLarge: 'Groot',
    aiFontSizeXLarge: 'Extra groot',
    aiFontSizeCustom: 'Aangepast',
    aiPanelSideLeft: 'Links',
    aiPanelSideRight: 'Rechts',
    setAiPanelSide: 'Positie AI-zijbalk',
    setAiFontSize: 'Tekstgrootte AI-paneel',
    setAiSpellcheck: 'Spellingcontrole in AI-chat',
    setAiSpellcheckDesc:
      'Onderstreept verkeerd gespelde woorden tijdens het typen in het AI-chatveld.',
    setDefaultApp: 'Standaardapp voor Office-documenten',
    setDefaultAppFailed: 'Wijzigen is niet gelukt. Stel dit in via de systeeminstellingen.',
    setDefaultAppIs: 'BP Office is al de standaardapp.',
    setDefaultAppOther: 'Huidige standaard: {app}',
    setDefaultAppDesc: '.docx-, .xlsx- en .pdf-bestanden in BP Office openen bij dubbelklikken.',
    setDefaultAppOpenSettings: 'Systeeminstellingen openen',
    setDefaultAppSet: 'Als standaard instellen',
  },
  ms: {
    newHtml: 'AI HTML',
    newPdf: 'AI PDF',
    removeFolderRoot: 'Buang daripada senarai',
    addFolderRoot: 'Tambah folder…',
    rootUnavailable: 'Tidak tersedia',
    cloudSortRecent: 'Terbaru',
    cloudSortOldest: 'Terlama',
    aiFontSizeDefault: 'Lalai',
    aiFontSizeLarge: 'Besar',
    aiFontSizeXLarge: 'Sangat besar',
    aiFontSizeCustom: 'Tersuai',
    aiPanelSideLeft: 'Kiri',
    aiPanelSideRight: 'Kanan',
    setAiPanelSide: 'Kedudukan bar sisi AI',
    setAiFontSize: 'Saiz teks panel AI',
    setAiSpellcheck: 'Semakan ejaan dalam sembang AI',
    setAiSpellcheckDesc:
      'Gariskan perkataan yang salah ejaan semasa menaip dalam kotak sembang AI.',
    setDefaultApp: 'Apl lalai untuk dokumen Office',
    setDefaultAppFailed: 'Tidak dapat mengubahnya. Tetapkan dalam tetapan sistem.',
    setDefaultAppIs: 'BP Office sudah menjadi apl lalai.',
    setDefaultAppOther: 'Lalai semasa: {app}',
    setDefaultAppDesc: 'Buka fail .docx, .xlsx dan .pdf dalam BP Office apabila diklik dua kali.',
    setDefaultAppOpenSettings: 'Buka tetapan sistem',
    setDefaultAppSet: 'Jadikan lalai',
  },
  he: {
    newHtml: 'AI HTML',
    newPdf: 'AI PDF',
    removeFolderRoot: 'הסרה מהרשימה',
    addFolderRoot: 'הוספת תיקייה…',
    rootUnavailable: 'לא זמין',
    cloudSortRecent: 'החדשים ביותר',
    cloudSortOldest: 'הישנים ביותר',
    aiFontSizeDefault: 'ברירת מחדל',
    aiFontSizeLarge: 'גדול',
    aiFontSizeXLarge: 'גדול מאוד',
    aiFontSizeCustom: 'מותאם אישית',
    aiPanelSideLeft: 'שמאל',
    aiPanelSideRight: 'ימין',
    setAiPanelSide: 'מיקום סרגל הצד של הבינה המלאכותית',
    setAiFontSize: 'גודל הטקסט בחלונית ה-AI',
    setAiSpellcheck: 'בדיקת איות בצ׳אט ה-AI',
    setAiSpellcheckDesc: 'סימון מילים עם שגיאות כתיב בעת הקלדה בתיבת הצ׳אט של ה-AI.',
    setDefaultApp: 'אפליקציית ברירת המחדל למסמכי Office',
    setDefaultAppFailed: 'לא ניתן לשנות. יש להגדיר בהגדרות המערכת.',
    setDefaultAppIs: 'BP Office היא כבר ברירת המחדל.',
    setDefaultAppOther: 'ברירת המחדל הנוכחית: {app}',
    setDefaultAppDesc: 'פתיחת קובצי .docx‏, .xlsx ו‑.pdf ב‑BP Office בלחיצה כפולה.',
    setDefaultAppOpenSettings: 'פתיחת הגדרות המערכת',
    setDefaultAppSet: 'הגדרה כברירת מחדל',
  },
  hi: {
    newHtml: 'AI HTML',
    newPdf: 'AI PDF',
    removeFolderRoot: 'सूची से हटाएँ',
    addFolderRoot: 'फ़ोल्डर जोड़ें…',
    rootUnavailable: 'उपलब्ध नहीं',
    cloudSortRecent: 'हाल के',
    cloudSortOldest: 'सबसे पुराने',
    aiFontSizeDefault: 'डिफ़ॉल्ट',
    aiFontSizeLarge: 'बड़ा',
    aiFontSizeXLarge: 'बहुत बड़ा',
    aiFontSizeCustom: 'कस्टम',
    aiPanelSideLeft: 'बाईं ओर',
    aiPanelSideRight: 'दाईं ओर',
    setAiPanelSide: 'AI साइडबार की स्थिति',
    setAiFontSize: 'AI पैनल का टेक्स्ट आकार',
    setAiSpellcheck: 'AI चैट में वर्तनी जाँच',
    setAiSpellcheckDesc: 'AI चैट इनपुट में टाइप करते समय गलत वर्तनी वाले शब्दों को रेखांकित करें।',
    setDefaultApp: 'Office दस्तावेज़ों के लिए डिफ़ॉल्ट ऐप',
    setDefaultAppFailed: 'बदला नहीं जा सका। कृपया सिस्टम सेटिंग में सेट करें।',
    setDefaultAppIs: 'BP Office पहले से डिफ़ॉल्ट ऐप है।',
    setDefaultAppOther: 'वर्तमान डिफ़ॉल्ट: {app}',
    setDefaultAppDesc: '.docx, .xlsx और .pdf फ़ाइलें डबल-क्लिक करने पर BP Office में खोलें।',
    setDefaultAppOpenSettings: 'सिस्टम सेटिंग खोलें',
    setDefaultAppSet: 'डिफ़ॉल्ट बनाएँ',
  },
  'zh-TW': {
    newHtml: 'AI HTML',
    newPdf: 'AI PDF',
    removeFolderRoot: '從清單移除',
    addFolderRoot: '加入資料夾…',
    rootUnavailable: '無法使用',
    cloudSortRecent: '最近',
    cloudSortOldest: '最早',
    aiFontSizeDefault: '預設',
    aiFontSizeLarge: '大',
    aiFontSizeXLarge: '特大',
    aiFontSizeCustom: '自訂',
    aiPanelSideLeft: '左側',
    aiPanelSideRight: '右側',
    setAiPanelSide: 'AI 側邊欄位置',
    setAiFontSize: 'AI 面板文字大小',
    setAiSpellcheck: 'AI 對話拼字檢查',
    setAiSpellcheckDesc: '在 AI 對話輸入框中輸入時標示拼錯的單字。',
    setDefaultApp: '設為 Office 文件預設程式',
    setDefaultAppFailed: '設定失敗，請在系統設定中手動更改。',
    setDefaultAppIs: 'BP Office 已是預設程式。',
    setDefaultAppOther: '目前預設程式：{app}',
    setDefaultAppDesc: '雙擊 .docx、.xlsx、.pdf 檔案時用 BP Office 開啟。',
    setDefaultAppOpenSettings: '開啟系統設定',
    setDefaultAppSet: '設為預設',
  },
} as const
